# Generated by Django 5.0.1 on 2024-03-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userverification_delete_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='2bede7ea931b845598bcdb48a0c34b7d', max_length=255),
        ),
    ]
