version: '3.9'
services:
  database:
    build: .
    ports:
      - "3307:3306"
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
volumes:
  redis_volume_data:
  