# Generated by Django 5.0.1 on 2024-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='icon_default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default="Hi i'm using chatapp-hgbaodev", max_length=255),
        ),
    ]
