# Generated by Django 5.0.1 on 2024-01-26 01:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_profile_photo_alter_profile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='groupName can only contains letter and space.', regex='^[a-zA-Z ]+$'), django.core.validators.MinLengthValidator(limit_value=8, message='groupName must have at least 8 characters.'), django.core.validators.MaxLengthValidator(limit_value=100, message='groupName can only have a maximum of 100 characters.')])),
                ('avatar', models.TextField(default='link_to_default_avatar')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joineddAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group_id', 'user_id')},
            },
        ),
    ]
