# Generated by Django 5.0.1 on 2024-01-26 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_rename_group_id_groupmember_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='groupName can only contains letter and space.', regex='^[a-zA-Z ]+$'), django.core.validators.MinLengthValidator(limit_value=8, message='groupName must have at least 8 characters.'), django.core.validators.MaxLengthValidator(limit_value=100, message='groupName can only have a maximum of 100 characters.')]),
        ),
    ]
