# Generated by Django 5.0.1 on 2024-03-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='user_id',
            new_name='user',
        ),
    ]
