# Generated by Django 5.0.1 on 2024-03-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_creator_id_conversation_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chanel_id',
        ),
    ]
