# Generated by Django 5.0.1 on 2024-03-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_participants_conversation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='conversation_title',
            new_name='title',
        ),
    ]
