# Generated by Django 5.0.1 on 2024-03-14 09:10

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.IntegerField(choices=[(1, 'GROUP'), (2, 'FRIEND')], default=chat.models.Conversation.ConversationType['GROUP']),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'IMAGE'), (3, 'VIDEO'), (4, 'AUDIO'), (5, 'FILE')], default=chat.models.Message.MessageType['TEXT']),
        ),
    ]
