# Generated by Django 5.0.1 on 2024-03-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_type_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='image',
            field=models.CharField(default='07adfb1c92adb6b369b44cf6f1734a52', max_length=255),
        ),
    ]
