# Generated by Django 5.0.1 on 2024-03-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_messages', to='chat.message'),
        ),
    ]
