# Generated by Django 5.0.1 on 2024-03-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
