# Generated by Django 5.0.1 on 2024-03-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_conversation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
