# Generated by Django 5.0.1 on 2024-03-25 18:13

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_pinconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'IMAGE'), (3, 'VIDEO'), (4, 'AUDIO'), (5, 'DOCUMENT'), (6, 'RECALL')], default=chat.models.Message.MessageType['TEXT']),
        ),
    ]
