# Generated by Django 5.0.1 on 2024-03-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_message_attachment_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='Attachments',
        ),
    ]
