# Generated by Django 5.0.1 on 2024-03-25 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_rename_attachment_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
