# Generated by Django 5.0.1 on 2024-03-26 08:37

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_attachments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'IMAGE'), (3, 'VIDEO'), (4, 'AUDIO'), (5, 'DOCUMENT'), (6, 'RECALL'), (7, 'INIT_CONVERSATION'), (8, 'CLOSE_CONVERSATION')], default=chat.models.Message.MessageType['TEXT']),
        ),
    ]
