# Generated by Django 5.0.1 on 2024-04-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_message_message_type_namecard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='creator',
            new_name='admin',
        ),
    ]
