# Generated by Django 5.0.1 on 2024-04-04 07:30

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_rename_creator_conversation_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'IMAGE'), (3, 'VIDEO'), (4, 'AUDIO'), (5, 'DOCUMENT'), (6, 'RECALL'), (7, 'NEWS'), (8, 'NAMECARD'), (9, 'VIDEOCALL')], default=chat.models.Message.MessageType['TEXT']),
        ),
        migrations.CreateModel(
            name='CallMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('ended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
        ),
    ]
