# Generated by Django 5.0.1 on 2024-04-20 07:05

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_alter_message_message_type_callmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'IMAGE'), (3, 'VIDEO'), (4, 'AUDIO'), (5, 'DOCUMENT'), (6, 'RECALL'), (7, 'NEWS'), (8, 'NAMECARD'), (9, 'VIDEOCALL'), (10, 'VOICECALL')], default=chat.models.Message.MessageType['TEXT']),
        ),
    ]
