# Generated by Django 5.0.1 on 2024-02-02 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='groupName can only contains letter and space.', regex='^[a-zA-Z ]+$'), django.core.validators.MinLengthValidator(limit_value=8, message='groupName must have at least 8 characters.'), django.core.validators.MaxLengthValidator(limit_value=100, message='groupName can only have a maximum of 100 characters.')])),
                ('avatar', models.CharField(default='group_default.png', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
